name: Build and deploy docker image to DockerHub - snitching-confessions-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: 
      name: 'Development'

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: bingodeevee/snitching-confessions-dockerfork:${{ github.run_id }}-devbuild


  prod:
    runs-on: ubuntu-latest
    environment: 
      name: 'Production'
    needs: dev

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: bingodeevee/snitching-confessions-dockerfork:latest